apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotappo-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotappo-analytics
  template:
    metadata:
      labels:
        app: rotappo-analytics
    spec:
      containers:
        - name: analytics
          image: rotappo-analytics:latest
          args: ["analytics-service"]
          ports:
            - containerPort: 50051
