apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotappo-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotappo-ml
  template:
    metadata:
      labels:
        app: rotappo-ml
    spec:
      containers:
        - name: ml
          image: rotappo-ml:latest
          args: ["ml-service"]
          ports:
            - containerPort: 50052
