apiVersion: v1
kind: Service
metadata:
  name: rotappo-analytics
spec:
  selector:
    app: rotappo-analytics
  ports:
    - port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: rotappo-ml
spec:
  selector:
    app: rotappo-ml
  ports:
    - port: 50052
      targetPort: 50052
