[tasks.check-crate-core-ports]
workspace = false
command = "cargo"
args = ["check", "-p", "phenome-ports"]

[tasks.test-crate-core-ports]
workspace = false
command = "cargo"
args = ["test", "-p", "phenome-ports"]
